version: '3'

services:

  nginx:
    restart: always
    build:
      context: ./docker/container/nginx
    volumes:
      - ./:/var/www/vault:cached
      - ./storage/logs/nginx:/var/log/nginx
    ports:
      - "${EXT_HTTP_PORT:-80}:80"
    depends_on:
      - php-fpm

  php-fpm:
    restart: always
    build:
      context: ./docker/container/php-fpm
    volumes:
      - ./:/var/www/vault:cached
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./docker/.data/postgresql:/var/lib/postgresql/data
      - ./storage/logs/postgresql:/var/log/postgresql
    ports:
      - "${EXT_DB_PORT:-5433}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    restart: always
    image: redis

  workspace:
    restart: always
    tty: true
    build:
      context: ./docker/container/workspace
    volumes:
      - ./:/var/www/vault:cached
    depends_on:
      - postgres
      - redis
